package com.example.matheus.taskbar;

import android.content.Intent;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

//NOTE: ALL GRAPHICS GENERATED BY ME ON FLAMINGTEXT.COM, GIMP, OR ACQUIRED FROM PIXABAY.COM

public class MainActivity extends AppCompatActivity {

    public final String help_message = "Welcome, and thank you for downloading Tasker!\n\n" +
            "\n\nIMPORTANT: please read the help on each page at least once. " +
            "Some buttons have multiple functions which are explained in the help text." +
            "To set an alarm go to the alarm screen by clicking \"ALARM\" on the main " +
            "screen.\n\nTo manage your tasks go to the tasks screen by clicking \"TASKS\"" +
            " on the main screen.\n\nTo use the shopping list feature, simply click " +
            "\"SHOPPING LIST\" on the main screen.\n\nEach screen also has additional help" +
            " that can be accessed by clicking the \"?\" button on screen.\n\nFor questions/" +
            "issues please e-mail Matheus (asaph@okstate.edu).";

    public String app_name_str = "Tasker";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getSupportActionBar( ).setTitle( "Main" );

        Button shopping = ( Button ) this.findViewById( R.id.slist_button );
        shopping.setOnClickListener( new Button.OnClickListener( ) {
            @Override
            public void onClick( View view ) {
                Intent intent = new Intent( getApplicationContext( ), ShoppingListActivity.class );
                startActivity( intent );
            }
        });
    }

    //set as the onClick listener for all
    //buttons in this activity
    public void button_click_listener( View view ) {
        if( view == this.findViewById( R.id.tasks_button ) ) { //if tasks is pressed
            Intent intent = new Intent( this, Tasks.class );   //create intent object
            startActivity( intent );                           //go to tasks activity
        }
        else if( view == this.findViewById( R.id.help_button ) ) { //if help is pressed
            show_help_pop( );
        }
        else if( view == this.findViewById( R.id.alarm_button ) ) { //if alarm is pressed
            //Toast.makeText( getApplicationContext( ), "alarm feature not implemented yet", Toast.LENGTH_SHORT ).show( );
            Intent intent = new Intent( this, Alarm.class );
            startActivity( intent );
        }
    }

    //shows a pop-up with some help information
    public void show_help_pop( ) {
        //create and set up dialog box object
        AlertDialog.Builder pop_up = new AlertDialog.Builder( this );
        pop_up.setTitle( app_name_str + " Help" );
        pop_up.setIcon( R.drawable.logo );
        pop_up.setMessage( help_message );

        //set up buttons for dialog box
        pop_up.setPositiveButton( "OK", null );

        //show pop-up
        pop_up.show( );
    }
}

